name: CICD

on:
  push:
    branches: [main,master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run : npm install
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t kaungmyathan/nodejs-ec2-github-actions .
      - name: Publish image to docker hub
        run: docker push kaungmyathan/nodejs-ec2-github-actions:latest
  deploy:
    needs: build
    runs-on: [ip-172-31-46-114]
    steps:
      - name: Pull image from docker hub
        run: docker pull kaungmyathan/nodejs-ec2-github-actions
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 -name nodejs-app-container kaungmyathan/nodejs-ec2-github-actions